<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <Folder Include="Components\Forms\" />
    <Folder Include="Components\Modals\" />
    <Folder Include="Components\Shared\" />
    <Folder Include="Models\" />
    <Folder Include="Interfaces\" />
    <Folder Include="Helpers\" />
    <Folder Include="Auth\" />
    <Folder Include="Layout\" />
    <Folder Include="Pages\Companies\" />
    <Folder Include="Pages\Users\" />
    <Folder Include="Pages\Rooms\" />
    <Folder Include="Pages\Reservations\" />
    <Folder Include="Services\" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\src\Shared\MeetingReservation.Communication\MeetingReservation.Communication.csproj" />
  </ItemGroup>

</Project>
