//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MeetingReservation.Exceptions {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ResourceMessagesException {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourceMessagesException() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MeetingReservation.Exceptions.ResourceMessagesException", typeof(ResourceMessagesException).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company not found..
        /// </summary>
        public static string COMPANY_NOT_FOUND {
            get {
                return ResourceManager.GetString("COMPANY_NOT_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The description must be less than 255 characters..
        /// </summary>
        public static string DESCRIPTION_TOO_LONGER {
            get {
                return ResourceManager.GetString("DESCRIPTION_TOO_LONGER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email already registered..
        /// </summary>
        public static string EMAIL_ALREADY_REGISTERED {
            get {
                return ResourceManager.GetString("EMAIL_ALREADY_REGISTERED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-mail or password invalid..
        /// </summary>
        public static string EMAIL_OR_PASSWORD_INVALID {
            get {
                return ResourceManager.GetString("EMAIL_OR_PASSWORD_INVALID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Capacity can&apos;t be empty..
        /// </summary>
        public static string EMPTY_CAPACITY {
            get {
                return ResourceManager.GetString("EMPTY_CAPACITY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-mail can&apos;t be empty..
        /// </summary>
        public static string EMPTY_EMAIL {
            get {
                return ResourceManager.GetString("EMPTY_EMAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name can&apos;t be empty..
        /// </summary>
        public static string EMPTY_NAME {
            get {
                return ResourceManager.GetString("EMPTY_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Participants can&apos;t be empty..
        /// </summary>
        public static string EMPTY_PARTICIPANTS {
            get {
                return ResourceManager.GetString("EMPTY_PARTICIPANTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password can&apos;t be empty..
        /// </summary>
        public static string EMPTY_PASSWORD {
            get {
                return ResourceManager.GetString("EMPTY_PASSWORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username can&apos;t be empty..
        /// </summary>
        public static string EMPTY_USERNAME {
            get {
                return ResourceManager.GetString("EMPTY_USERNAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You don&apos;t have permission to access this resource.
        /// </summary>
        public static string FORBIDDEN_ACCESS {
            get {
                return ResourceManager.GetString("FORBIDDEN_ACCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initial time must be earlier than end time..
        /// </summary>
        public static string INITIAL_TIME_MUST_BE_EARLIER {
            get {
                return ResourceManager.GetString("INITIAL_TIME_MUST_BE_EARLIER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-mail should be valid..
        /// </summary>
        public static string INVALID_EMAIL {
            get {
                return ResourceManager.GetString("INVALID_EMAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authentication token is missing..
        /// </summary>
        public static string NO_TOKEN {
            get {
                return ResourceManager.GetString("NO_TOKEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password different from the current password.
        /// </summary>
        public static string PASSWORD_DIFFERENT_CURRENT_PASSWORD {
            get {
                return ResourceManager.GetString("PASSWORD_DIFFERENT_CURRENT_PASSWORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password must be at least 6 digits long..
        /// </summary>
        public static string PASSWORD_LONGER_THAN_SIX {
            get {
                return ResourceManager.GetString("PASSWORD_LONGER_THAN_SIX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reservation not found..
        /// </summary>
        public static string RESERVATION_NOT_FOUND {
            get {
                return ResourceManager.GetString("RESERVATION_NOT_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The selected time slot is already reserved for this room..
        /// </summary>
        public static string RESERVATION_OCCUPIED {
            get {
                return ResourceManager.GetString("RESERVATION_OCCUPIED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role is not supported..
        /// </summary>
        public static string ROLE_NOT_SUPPORTED {
            get {
                return ResourceManager.GetString("ROLE_NOT_SUPPORTED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Room not found..
        /// </summary>
        public static string ROOM_NOT_FOUND {
            get {
                return ResourceManager.GetString("ROOM_NOT_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown error!.
        /// </summary>
        public static string UNKNOWN_ERROR {
            get {
                return ResourceManager.GetString("UNKNOWN_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User not found..
        /// </summary>
        public static string USER_NOT_FOUND {
            get {
                return ResourceManager.GetString("USER_NOT_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User without permission to access this resource..
        /// </summary>
        public static string USER_WITHOUT_PERMISSION_ACCESS_RESOURCE {
            get {
                return ResourceManager.GetString("USER_WITHOUT_PERMISSION_ACCESS_RESOURCE", resourceCulture);
            }
        }
    }
}
