<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="9.0.11" />
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="9.0.8" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="9.0.6" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Shared\MeetingReservation.Communication\MeetingReservation.Communication.csproj" />
    <ProjectReference Include="..\..\Shared\MeetingReservation.Exceptions\MeetingReservation.Exceptions.csproj" />
    <ProjectReference Include="..\MeetingReservation.Application\MeetingReservation.Application.csproj" />
    <ProjectReference Include="..\MeetingReservation.Infrastructure\MeetingReservation.Infrastructure.csproj" />
  </ItemGroup>

</Project>
